# Generated by Django 5.0.6 on 2024-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='groups',
            field=models.ManyToManyField(blank=True, to='games_sessions.group'),
        ),
    ]
