# Generated by Django 5.0.7 on 2024-07-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_sessions', '0002_group_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
    ]
