# Generated by Django 5.0.6 on 2024-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_sessions', '0003_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('not_started', 'Non commencé'), ('active', 'En cours'), ('paused', 'En pause'), ('finished', 'Terminé')], default='not_started', max_length=20),
        ),
    ]
