# Generated by Django 5.0.6 on 2024-07-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_sessions', '0004_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='current_phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
