# Generated by Django 5.0.6 on 2024-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_sessions', '0005_remove_group_name_group_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
