# Generated by Django 5.0.6 on 2024-07-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_project_group'),
        ('games_sessions', '0006_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group', to='games.project'),
        ),
    ]
