# Generated by Django 5.0.6 on 2024-07-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gamephase_group'),
        ('games_sessions', '0007_group_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='games.gamephase'),
        ),
    ]
