# Generated by Django 5.0.6 on 2024-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_sessions', '0008_alter_group_current_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='games_sessions.group'),
        ),
    ]
