# Generated by Django 5.0.6 on 2024-07-10 11:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games_sessions', '0006_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('business_value', models.IntegerField()),
                ('time_estimation', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_sessions.group')),
            ],
        ),
        migrations.CreateModel(
            name='GamePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('pending', 'En attente de validation'), ('completed', 'Complété'), ('wrong', 'Fausse réponse'), ('correct_waiting', 'Juste, en attente'), ('wrong_waiting', 'Fausse, en attente'), ('finished', 'Terminé')], default='not_started', max_length=20)),
                ('requires_validation', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_progress', models.DurationField(default=datetime.timedelta)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('effect', models.JSONField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('business_value', models.IntegerField()),
                ('time_estimation', models.DurationField()),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='games.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='SprintUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_estimation', models.DurationField()),
                ('completed', models.BooleanField(default=False)),
                ('progress_time', models.DurationField(default=datetime.timedelta)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sprint')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.userstory')),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='user_stories',
            field=models.ManyToManyField(related_name='related_sprints', through='games.SprintUserStory', to='games.userstory'),
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
                ('user_stories', models.ManyToManyField(to='games.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='BacklogTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_stories', models.ManyToManyField(to='games.userstorytemplate')),
            ],
        ),
    ]
