# Generated by Django 5.0.6 on 2024-07-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('games_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphasestatus',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_statuses', to='games_sessions.group'),
        ),
        migrations.AddField(
            model_name='groupphasestatus',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_statuses', to='games.gamephase'),
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project', to='games_sessions.group'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.project'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project'),
        ),
        migrations.AddField(
            model_name='event',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sprint'),
        ),
        migrations.AddField(
            model_name='sprintuserstory',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sprint'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='games.backlog'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='games.sprint'),
        ),
        migrations.AddField(
            model_name='sprintuserstory',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.userstory'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='user_stories',
            field=models.ManyToManyField(related_name='related_sprints', through='games.SprintUserStory', to='games.userstory'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='stories',
            field=models.ManyToManyField(related_name='backlogs', to='games.userstory'),
        ),
        migrations.AddField(
            model_name='backlogtemplate',
            name='user_stories',
            field=models.ManyToManyField(to='games.userstorytemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='groupphasestatus',
            unique_together={('group', 'phase')},
        ),
    ]
