# Generated by Django 5.0.6 on 2024-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamephase',
            name='project',
        ),
        migrations.AddField(
            model_name='gamephase',
            name='requires_validation',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
