# Generated by Django 5.0.6 on 2024-07-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_project_group'),
        ('games_sessions', '0007_group_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamephase',
            name='project',
        ),
        migrations.AddField(
            model_name='gamephase',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games_sessions.group'),
            preserve_default=False,
        ),
    ]
