# Generated by Django 5.0.6 on 2024-07-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_gamephase_project_and_more'),
        ('games_sessions', '0006_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('business_value', models.IntegerField()),
                ('time_estimation', models.DurationField()),
            ],
        ),
        migrations.RenameField(
            model_name='gamephase',
            old_name='correct_answer',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_sessions.group')),
            ],
        ),
        migrations.AddField(
            model_name='gamephase',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.project'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('effect', models.JSONField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('business_value', models.IntegerField()),
                ('time_estimation', models.DurationField()),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
            ],
        ),
        migrations.CreateModel(
            name='SprintUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('time_estimation', models.DurationField()),
                ('completed', models.BooleanField(default=False)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sprint')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.userstory')),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='user_stories',
            field=models.ManyToManyField(through='games.SprintUserStory', to='games.userstory'),
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.project')),
                ('user_stories', models.ManyToManyField(to='games.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='BacklogTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_stories', models.ManyToManyField(to='games.userstorytemplate')),
            ],
        ),
    ]
