# Generated by Django 5.0.6 on 2024-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_backlog_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
