# Generated by Django 5.0.7 on 2024-07-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_eventtemplate_remove_event_sprint_event_answer_and_more'),
        ('games_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_1_answer', models.JSONField(blank=True, null=True)),
                ('phase_2_answer', models.JSONField(blank=True, null=True)),
                ('completed_user_story_ids', models.JSONField(blank=True, null=True)),
                ('created_user_stories', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_game_data', to='games_sessions.group')),
            ],
        ),
    ]
