# Generated by Django 5.0.6 on 2024-07-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_userstory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_sprint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint_number',
            field=models.IntegerField(default=1),
        ),
    ]
