# Generated by Django 5.0.6 on 2024-07-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gamephase_group'),
        ('games_sessions', '0008_alter_group_current_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamephase',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='gamephase',
            name='status',
        ),
        migrations.CreateModel(
            name='GroupPhaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('pending', 'En attente de validation'), ('completed', 'Complété'), ('wrong', 'Fausse réponse'), ('correct_waiting', 'Juste, en attente'), ('wrong_waiting', 'Fausse, en attente'), ('finished', 'Terminé')], default='not_started', max_length=20)),
                ('answer', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_statuses', to='games_sessions.group')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_statuses', to='games.gamephase')),
            ],
            options={
                'unique_together': {('group', 'phase')},
            },
        ),
    ]
