# Generated by Django 5.0.7 on 2024-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_savedgamedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedgamedata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='savedgamedata',
            name='current_sprint',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
