# Generated by Django 5.0.6 on 2024-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_gamephase_answer_remove_gamephase_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupphasestatus',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
