# Generated by Django 5.0.6 on 2024-07-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_project_current_sprint_userstory_sprint_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='has_been_created',
            field=models.BooleanField(default=False),
        ),
    ]
