# Generated by Django 5.0.7 on 2024-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_savedgamedata_completed_user_story_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgamedata',
            name='original_sprint_numbers',
            field=models.JSONField(default=dict),
        ),
    ]
