# Generated by Django 5.0.6 on 2024-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_groupphasestatus_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupphasestatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('pending', 'En attente de validation'), ('completed', 'Complété'), ('wrong', 'Fausse réponse'), ('correct_waiting', 'Juste, en attente'), ('wrong_waiting', 'Fausse, en attente')], default='not_started', max_length=20),
        ),
    ]
