# Generated by Django 5.0.7 on 2024-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_savedgamedata_original_sprint_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='current_progress',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='progress_time',
            field=models.DurationField(default=0),
        ),
    ]
