# Generated by Django 5.0.7 on 2024-07-29 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_sprint_current_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='current_progress',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='progress_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
