# Generated by Django 5.0.6 on 2024-07-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_sprintuserstory_sprint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='sprint_number',
            new_name='original_sprint_number',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='project',
        ),
        migrations.AddField(
            model_name='sprint',
            name='backlog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.backlog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='sprint_number',
            field=models.IntegerField(default=1),
        ),
    ]
