# Generated by Django 5.0.6 on 2024-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_groupphasestatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='product_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scrum_master',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
