# Generated by Django 5.0.6 on 2024-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_sprint_number_userstory_original_sprint_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sprint',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
