# Generated by Django 5.0.7 on 2024-08-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_sprint_current_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_event_project', to='games.event'),
        ),
    ]
