# Generated by Django 5.0.6 on 2024-07-21 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_sprint_end_time_remove_sprint_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='progress_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='original_sprint_number',
            field=models.IntegerField(default=0),
        ),
    ]
