# Generated by Django 5.0.7 on 2024-08-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_project_current_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_client_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_comments', to='games.event'),
        ),
    ]
