# Generated by Django 5.0.6 on 2024-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_userstory_progress_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTimeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_hours', models.IntegerField(default=1)),
                ('real_minutes', models.IntegerField(default=1)),
            ],
        ),
    ]
