# Generated by Django 5.0.6 on 2024-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant')], default='etudiant', max_length=25),
        ),
    ]
